### ISSUE TITLE
Token endpoint - fetch returns empty response

### ISSUE THREAD

**Issue by AndrePinto-NET** [IdentityServer/IdentityServer4#3137]
It seems that the token endpoint does not play well if called using fetch, the response is always empty.

I did the same request then using JQuery ajax, and by using a XHR request I have a response. The funny thing is, everything is exactly the same, headers, form data, .etc.. (except the type of call, one is fetch and the other xhr).

When using fetch, I get a valid HTTP 200 (just like with xhr), but the response, like I mentioned before is empty.

Do not know how relevant it is, just though it would be nice to mention.

**Comment by brockallen** [comment]
Does fetch send app/json by default, rather than form-urlencoded?

**Comment by AndrePinto-NET** [comment]
I don't know the default value, but in any case I was forcing form-urlencoded (initially, I was infact sending app/json, but then I corrected it). 

The request was 1 to 1 to the XHR, I was making sure that all the headers and body had the exact same values.

**Comment by brockallen** [comment]
But then it still didn't work?

**Comment by AndrePinto-NET** [comment]
Yes, it did not worked, that's why I wrote here, thought this might be worth mentioning.

**Comment by brockallen** [comment]
I still don't know. A fiddler trace might be helpful. But without more info, there's not much I can do. I'll close for now, but if you have more info or find a bug, let us know.

**Comment by kmiskiewicz** [comment]
For sure your problem is already solved, but I'd like to leave an interesting information. I hit the same problem during Chrome Extension development. The token endpoint returned 200 and 0 bytes response. 
I was using fetch with necessary headers. After I found this issue I switched to the old XMLHttpRequest. This time I also got an empty response but also a warning "Cross-Origin Read Blocking (CORB) blocked cross-origin response". Here are details about this: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches So most probably your case was caused by the browser not the IdentityServer itself
