### ISSUE TITLE
Expired token and refresh token

### ISSUE THREAD

**Issue by ehsaanwelcome** [IdentityServer/IdentityServer4#556]
I am using identityserver 4 rc resource owner flow and have two issues which i am unable to solve through documentation
1. I get token successfully but when token is expired, i expect to get 401 unauthorized so that i could refresh token or ask credentials again but it redirect me to another page account/login which i dnt want because of SPA. How can i stop that behaviour?

2. Refresh token: i have configured client with offlineaccess and when i refresh token, i do send grant type refresh_token, scope offline_access along with clientid, secret and access token but get invalid grant type error

Can you please explain these to me
Thanks

**Comment by brockallen** [comment]
for 1: i don't understand.

for 2: what do the logs say?

**Comment by ehsaanwelcome** [comment]
for 1: 
1. i login using ResourceOwnerPassword flow and i got access token back which you can see in attached login image
2. one of my api have authorize attribute, i get back results as long as token is valid but as token gets expire (i did set expiry 2 mins for testing) then i get back html which is mvc razor view for login which you can see in attached expire image 
3. i should get simple message with 401 http status code which 

for 2:
if i will get 401 in above mentioned case then i would like to get refresh token without user involvement. i have attached refresh image where you can that what exactly i am sending

i have also attached startup file where you can see server configuration as well

[Desktop.zip](https://github.com/IdentityServer/IdentityServer4/files/638084/Desktop.zip)

**Comment by jrcpereira** [comment]
@ehsaanwelcome, to which endpoint are you making the refresh token request?
You should request it to Token Endpoint. If you're addressing it to the base identity server address, then you should receive an HTML response.
The token endpoint correctly responds with an 401 and an error message on body
> Error: Invalid grant

**Comment by ehsaanwelcome** [comment]
for 2: i figured out refresh token issue, actually i was sending access token in refresh token which should be refresh token so that's what is solved
one thing which i don't understand is that client secret is saved in javascript client (i am using resource owner password flow), it is not safe to have secret in javascript client, should i use any other flow?

for 1: when token is expired it redirects me to login page so i get login page with 200 status code but i want simple 401 unauthorized error (in SPA app) so that i can refresh token in background
i think, this is something ASPNETCORE MVC authorization settings where it redirects to login page in case of token is expired, i have attached log where it is redirecting to account/login

![untitled](https://cloud.githubusercontent.com/assets/2996859/21009998/0700642c-bd4a-11e6-81ce-50be2d15cb7d.png)

**Comment by cixonline** [comment]
Issue 1 is the exact same problem I'm also having. When my API method is called with an expired token, I get redirected to the login page which results in the client getting HTML back in the response with HTTP 200. I'm not sure if this is a configuration issue or an issue with the Authorize attribute but if so, it would be a nice feature request to have an option to tell it NOT to redirect on expired tokens. I can see the value of the redirect if you're going to a web page but not when calling an API method.

I'm having to hack around this in the client by checking to see if the response contains HTML instead of JSON but this seems wrong.

**Comment by ehsaanwelcome** [comment]
i solved that issue by having separate identity server website and Api's project otherwise both identity server and Api's client were in same project.

**Comment by cixonline** [comment]
Thanks! Like you, I had both IdentityServer and API in the same project. I suspect that doesn't really work in practice so I'll split them into separate projects and hopefully that will fix the issue.

**Comment by cixonline** [comment]
Can you share your Startup settings? I've split my projects but I'm still seeing the API project redirect to the IdentityServer4 project when the [Authorize] attribute detects an expired token. What specifically did you change that stopped the redirect?

**Comment by danielmeza** [comment]
What about check the token time life before to make te request?, the only issue here is the local time, but if the client change te local time in order to reusue an expired token it will recive and 401 error and a redirection to the login page. so you can simply check if the access_token is alive by it's life time attribute. if the token has expired then renewged it and get a new one.
